import Head from 'next/head'
import { memoryUsage } from 'process';

const Header = () => {

  return (
    <Head>
      <title></title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Header
